### lesson \#17 by Storchak Vasyl

# task 'Mine top 10 association rules worth recommending for [Groceries dataset](https://www.kaggle.com/heeraldedhia/groceries-dataset)'

In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import platform

from apyori import apriori

In [2]:
!which python3.12

/usr/bin/python3.12

In [3]:
print(platform.python_version())

3.12.11

In [4]:
##########################################################################

In [56]:
# dataset = df = pd.read_csv('Market_Basket_Optimisation.csv', header = None)
df = pd.read_csv('Groceries_dataset.csv')
df.head()

   Member_number        Date   itemDescription
0           1808  21-07-2015    tropical fruit
1           2552  05-01-2015        whole milk
2           2300  19-09-2015         pip fruit
3           1187  12-12-2015  other vegetables
4           3037  01-02-2015        whole milk

In [57]:
df.shape

(38765, 3)

In [61]:
# preparation data

In [58]:
df = df.drop(columns='Date')

In [59]:
df.shape

(38765, 2)

In [60]:
grouped = df.groupby('Member_number')['itemDescription'].apply(list).reset_index()
grouped

      Member_number                                    itemDescription
0              1000  [soda, canned beer, sausage, sausage, whole mi...
1              1001  [frankfurter, frankfurter, beef, sausage, whol...
2              1002  [tropical fruit, butter milk, butter, frozen v...
3              1003  [sausage, root vegetables, rolls/buns, deterge...
4              1004  [other vegetables, pip fruit, root vegetables,...
...             ...                                                ...
3893           4996  [dessert, salty snack, rolls/buns, misc. bever...
3894           4997  [tropical fruit, white wine, whole milk, curd,...
3895           4998                                 [rolls/buns, curd]
3896           4999  [bottled water, butter milk, tropical fruit, b...
3897           5000  [soda, bottled beer, fruit/vegetable juice, ro...

[3898 rows x 2 columns]

In [65]:
# shit pandas
grouped.iloc[0].iloc[1]

list

In [63]:
df = df.fillna(0)

In [67]:
# i decided to leave the duplicates!
trans = [grouped.iloc[row].iloc[1] for row in range(grouped.shape[0])]
trans[:5]

[['soda',
  'canned beer',
  'sausage',
  'sausage',
  'whole milk',
  'whole milk',
  'pickled vegetables',
  'misc. beverages',
  'semi-finished bread',
  'hygiene articles',
  'yogurt',
  'pastry',
  'salty snack'],
 ['frankfurter',
  'frankfurter',
  'beef',
  'sausage',
  'whole milk',
  'soda',
  'curd',
  'white bread',
  'whole milk',
  'soda',
  'whipped/sour cream',
  'rolls/buns'],
 ['tropical fruit',
  'butter milk',
  'butter',
  'frozen vegetables',
  'sugar',
  'specialty chocolate',
  'whole milk',
  'other vegetables'],
 ['sausage',
  'root vegetables',
  'rolls/buns',
  'detergent',
  'frozen meals',
  'rolls/buns',
  'dental care',
  'rolls/buns'],
 ['other vegetables',
  'pip fruit',
  'root vegetables',
  'canned beer',
  'rolls/buns',
  'whole milk',
  'other vegetables',
  'hygiene articles',
  'whole milk',
  'whole milk',
  'frozen fish',
  'red/blush wine',
  'chocolate',
  'shopping bags',
  'dish cleaner',
  'packaged fruit/vegetables',
  'tropical fruit',
  'rolls/buns',
  'cling film/bags',
  'chocolate',
  'pastry']]

In [68]:
# i let def settings from example
rules = list(apriori(trans, min_support=0.003, min_confidence=0.2, min_lift=4, min_length=2))
rules

[RelationRecord(items=frozenset({'beverages', 'canned beer', 'meat'}), support=0.0030785017957927143, ordered_statistics=[OrderedStatistic(items_base=frozenset({'beverages', 'canned beer'}), items_add=frozenset({'meat'}), confidence=0.27906976744186046, lift=4.3863465866466615)]),
 RelationRecord(items=frozenset({'red/blush wine', 'dessert', 'pastry'}), support=0.0035915854284248334, ordered_statistics=[OrderedStatistic(items_base=frozenset({'red/blush wine', 'pastry'}), items_add=frozenset({'dessert'}), confidence=0.358974358974359, lift=4.152172258997185)]),
 RelationRecord(items=frozenset({'whole milk', 'meat spreads', 'domestic eggs'}), support=0.0033350436121087736, ordered_statistics=[OrderedStatistic(items_base=frozenset({'meat spreads'}), items_add=frozenset({'whole milk', 'domestic eggs'}), confidence=0.37142857142857144, lift=5.284045881126173)]),
 RelationRecord(items=frozenset({'onions', 'sausage', 'sliced cheese'}), support=0.0035915854284248334, ordered_statistics=[OrderedStatistic(items_base=frozenset({'onions', 'sausage'}), items_add=frozenset({'sliced cheese'}), confidence=0.2121212121212121, lift=4.093309330933093)]),
 RelationRecord(items=frozenset({'sugar', 'other vegetables', 'spread cheese'}), support=0.0030785017957927143, ordered_statistics=[OrderedStatistic(items_base=frozenset({'other vegetables', 'spread cheese'}), items_add=frozenset({'sugar'}), confidence=0.26666666666666666, lift=4.04461738002594)]),
 RelationRecord(items=frozenset({'frankfurter', 'other vegetables', 'margarine', 'UHT-milk'}), support=0.0030785017957927143, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frankfurter', 'UHT-milk'}), items_add=frozenset({'margarine', 'other vegetables'}), confidence=0.20338983050847456, lift=4.065710560625814), OrderedStatistic(items_base=frozenset({'margarine', 'UHT-milk'}), items_add=frozenset({'frankfurter', 'other vegetables'}), confidence=0.2608695652173913, lift=4.2725611983924)]),
 RelationRecord(items=frozenset({'shopping bags', 'bottled water', 'berries', 'pip fruit'}), support=0.0030785017957927143, ordered_statistics=[OrderedStatistic(items_base=frozenset({'shopping bags', 'bottled water', 'pip fruit'}), items_add=frozenset({'berries'}), confidence=0.32432432432432434, lift=4.0650039106630755)]),
 RelationRecord(items=frozenset({'yogurt', 'pork', 'bottled water', 'berries'}), support=0.0033350436121087736, ordered_statistics=[OrderedStatistic(items_base=frozenset({'yogurt', 'pork', 'bottled water'}), items_add=frozenset({'berries'}), confidence=0.325, lift=4.07347266881029)]),
 RelationRecord(items=frozenset({'pip fruit', 'other vegetables', 'berries', 'fruit/vegetable juice'}), support=0.0038481272447408927, ordered_statistics=[OrderedStatistic(items_base=frozenset({'berries', 'pip fruit'}), items_add=frozenset({'other vegetables', 'fruit/vegetable juice'}), confidence=0.21126760563380284, lift=4.017176228100309), OrderedStatistic(items_base=frozenset({'pip fruit', 'other vegetables', 'fruit/vegetable juice'}), items_add=frozenset({'berries'}), confidence=0.3191489361702127, lift=4.00013682698228)]),
 RelationRecord(items=frozenset({'rolls/buns', 'beverages', 'oil', 'other vegetables'}), support=0.0030785017957927143, ordered_statistics=[OrderedStatistic(items_base=frozenset({'rolls/buns', 'beverages', 'other vegetables'}), items_add=frozenset({'oil'}), confidence=0.22641509433962265, lift=4.0671245978610555), OrderedStatistic(items_base=frozenset({'rolls/buns', 'oil', 'other vegetables'}), items_add=frozenset({'beverages'}), confidence=0.3076923076923077, lift=4.956134774316593)]),
 RelationRecord(items=frozenset({'sausage', 'waffles', 'tropical fruit', 'bottled beer'}), support=0.0033350436121087736, ordered_statistics=[OrderedStatistic(items_base=frozenset({'sausage', 'waffles'}), items_add=frozenset({'tropical fruit', 'bottled beer'}), confidence=0.2096774193548387, lift=4.894147189491983), OrderedStatistic(items_base=frozenset({'sausage', 'tropical fruit', 'bottled beer'}), items_add=frozenset({'waffles'}), confidence=0.29545454545454547, lift=4.281345049003042)]),
 RelationRecord(items=frozenset({'white bread', 'soda', 'bottled beer', 'whipped/sour cream'}), support=0.0033350436121087736, ordered_statistics=[OrderedStatistic(items_base=frozenset({'white bread', 'bottled beer'}), items_add=frozenset({'soda', 'whipped/sour cream'}), confidence=0.2, lift=4.124867724867725)]),
 RelationRecord(items=frozenset({'other vegetables', 'oil', 'bottled water', 'chocolate'}), support=0.0033350436121087736, ordered_statistics=[OrderedStatistic(items_base=frozenset({'oil', 'bottled water'}), items_add=frozenset({'other vegetables', 'chocolate'}), confidence=0.2452830188679245, lift=6.374088050314465), OrderedStatistic(items_base=frozenset({'oil', 'chocolate'}), items_add=frozenset({'other vegetables', 'bottled water'}), confidence=0.4482758620689655, lift=4.774260410778218), OrderedStatistic(items_base=frozenset({'other vegetables', 'bottled water', 'chocolate'}), items_add=frozenset({'oil'}), confidence=0.2452830188679245, lift=4.406051647682809), OrderedStatistic(items_base=frozenset({'other vegetables', 'oil', 'bottled water'}), items_add=frozenset({'chocolate'}), confidence=0.43333333333333335, lift=5.012265084075174)]),
 RelationRecord(items=frozenset({'sausage', 'citrus fruit', 'bottled water', 'sugar'}), support=0.0030785017957927143, ordered_statistics=[OrderedStatistic(items_base=frozenset({'sausage', 'citrus fruit', 'bottled water'}), items_add=frozenset({'sugar'}), confidence=0.3, lift=4.550194552529183)]),
 RelationRecord(items=frozenset({'yogurt', 'citrus fruit', 'bottled water', 'specialty chocolate'}), support=0.0038481272447408927, ordered_statistics=[OrderedStatistic(items_base=frozenset({'specialty chocolate', 'bottled water'}), items_add=frozenset({'yogurt', 'citrus fruit'}), confidence=0.2380952380952381, lift=4.088525277952591), OrderedStatistic(items_base=frozenset({'yogurt', 'specialty chocolate'}), items_add=frozenset({'citrus fruit', 'bottled water'}), confidence=0.24193548387096772, lift=5.3583211143695015), OrderedStatistic(items_base=frozenset({'yogurt', 'citrus fruit', 'bottled water'}), items_add=frozenset({'specialty chocolate'}), confidence=0.24193548387096772, lift=4.136247877758913)]),
 RelationRecord(items=frozenset({'canned beer', 'curd', 'other vegetables', 'salty snack'}), support=0.0030785017957927143, ordered_statistics=[OrderedStatistic(items_base=frozenset({'curd', 'salty snack'}), items_add=frozenset({'canned beer', 'other vegetables'}), confidence=0.27272727272727276, lift=4.057598889659959)]),
 RelationRecord(items=frozenset({'yogurt', 'other vegetables', 'cat food', 'fruit/vegetable juice'}), support=0.0030785017957927143, ordered_statistics=[OrderedStatistic(items_base=frozenset({'yogurt', 'cat food'}), items_add=frozenset({'other vegetables', 'fruit/vegetable juice'}), confidence=0.22641509433962265, lift=4.305200184077313)]),
 RelationRecord(items=frozenset({'rolls/buns', 'yogurt', 'chewing gum', 'domestic eggs'}), support=0.0035915854284248334, ordered_statistics=[OrderedStatistic(items_base=frozenset({'rolls/buns', 'chewing gum'}), items_add=frozenset({'yogurt', 'domestic eggs'}), confidence=0.2, lift=4.6130177514792905)]),
 RelationRecord(items=frozenset({'citrus fruit', 'oil', 'other vegetables', 'chocolate'}), support=0.0033350436121087736, ordered_statistics=[OrderedStatistic(items_base=frozenset({'oil', 'chocolate'}), items_add=frozenset({'citrus fruit', 'other vegetables'}), confidence=0.4482758620689655, lift=5.786024206439826), OrderedStatistic(items_base=frozenset({'citrus fruit', 'oil'}), items_add=frozenset({'other vegetables', 'chocolate'}), confidence=0.2452830188679245, lift=6.374088050314465), OrderedStatistic(items_base=frozenset({'citrus fruit', 'other vegetables', 'chocolate'}), items_add=frozenset({'oil'}), confidence=0.325, lift=5.838018433179723), OrderedStatistic(items_base=frozenset({'citrus fruit', 'oil', 'other vegetables'}), items_add=frozenset({'chocolate'}), confidence=0.43333333333333335, lift=5.012265084075174)]),
 RelationRecord(items=frozenset({'frankfurter', 'grapes', 'citrus fruit', 'other vegetables'}), support=0.0030785017957927143, ordered_statistics=[OrderedStatistic(items_base=frozenset({'grapes', 'citrus fruit'}), items_add=frozenset({'frankfurter', 'other vegetables'}), confidence=0.26666666666666666, lift=4.36750700280112)]),
 RelationRecord(items=frozenset({'rolls/buns', 'white bread', 'sausage', 'dessert'}), support=0.0033350436121087736, ordered_statistics=[OrderedStatistic(items_base=frozenset({'white bread', 'dessert'}), items_add=frozenset({'rolls/buns', 'sausage'}), confidence=0.34210526315789475, lift=4.154287588129202)]),
 RelationRecord(items=frozenset({'rolls/buns', 'white bread', 'shopping bags', 'dessert'}), support=0.0033350436121087736, ordered_statistics=[OrderedStatistic(items_base=frozenset({'shopping bags', 'dessert'}), items_add=frozenset({'rolls/buns', 'white bread'}), confidence=0.2096774193548387, lift=5.56001755540926), OrderedStatistic(items_base=frozenset({'white bread', 'dessert'}), items_add=frozenset({'rolls/buns', 'shopping bags'}), confidence=0.34210526315789475, lift=4.975844461901021), OrderedStatistic(items_base=frozenset({'rolls/buns', 'shopping bags', 'dessert'}), items_add=frozenset({'white bread'}), confidence=0.48148148148148145, lift=5.424320274031256), OrderedStatistic(items_base=frozenset({'rolls/buns', 'white bread', 'shopping bags'}), items_add=frozenset({'dessert'}), confidence=0.36111111111111105, lift=4.176887570062644)]),
 RelationRecord(items=frozenset({'other vegetables', 'soda', 'waffles', 'hamburger meat'}), support=0.0033350436121087736, ordered_statistics=[OrderedStatistic(items_base=frozenset({'waffles', 'hamburger meat'}), items_add=frozenset({'soda', 'other vegetables'}), confidence=0.5416666666666666, lift=4.362431129476584)]),
 RelationRecord(items=frozenset({'waffles', 'pork', 'other vegetables', 'pip fruit'}), support=0.0030785017957927143, ordered_statistics=[OrderedStatistic(items_base=frozenset({'waffles', 'pork'}), items_add=frozenset({'other vegetables', 'pip fruit'}), confidence=0.3076923076923077, lift=4.253136933987998)]),
 RelationRecord(items=frozenset({'whole milk', 'waffles', 'pork', 'pip fruit'}), support=0.0035915854284248334, ordered_statistics=[OrderedStatistic(items_base=frozenset({'waffles', 'pork'}), items_add=frozenset({'whole milk', 'pip fruit'}), confidence=0.358974358974359, lift=4.127675667498676)]),
 RelationRecord(items=frozenset({'whole milk', 'yogurt', 'waffles', 'sliced cheese'}), support=0.0030785017957927143, ordered_statistics=[OrderedStatistic(items_base=frozenset({'waffles', 'sliced cheese'}), items_add=frozenset({'whole milk', 'yogurt'}), confidence=0.8, lift=5.312436115843271), OrderedStatistic(items_base=frozenset({'whole milk', 'yogurt', 'sliced cheese'}), items_add=frozenset({'waffles'}), confidence=0.3, lift=4.347211895910781)]),
 RelationRecord(items=frozenset({'sausage', 'soda', 'rolls/buns', 'UHT-milk', 'yogurt'}), support=0.0030785017957927143, ordered_statistics=[OrderedStatistic(items_base=frozenset({'sausage', 'UHT-milk', 'soda'}), items_add=frozenset({'rolls/buns', 'yogurt'}), confidence=0.5, lift=4.490783410138248)]),
 RelationRecord(items=frozenset({'pork', 'other vegetables', 'beef', 'rolls/buns', 'yogurt'}), support=0.0033350436121087736, ordered_statistics=[OrderedStatistic(items_base=frozenset({'rolls/buns', 'yogurt', 'beef'}), items_add=frozenset({'pork', 'other vegetables'}), confidence=0.23636363636363636, lift=4.245831587767071)]),
 RelationRecord(items=frozenset({'pork', 'soda', 'beef', 'rolls/buns', 'yogurt'}), support=0.0030785017957927143, ordered_statistics=[OrderedStatistic(items_base=frozenset({'rolls/buns', 'yogurt', 'beef'}), items_add=frozenset({'soda', 'pork'}), confidence=0.2181818181818182, lift=4.777936670071502), OrderedStatistic(items_base=frozenset({'yogurt', 'soda', 'beef'}), items_add=frozenset({'rolls/buns', 'pork'}), confidence=0.2105263157894737, lift=4.435846372688478)]),
 RelationRecord(items=frozenset({'pork', 'whole milk', 'root vegetables', 'soda', 'beef'}), support=0.0030785017957927143, ordered_statistics=[OrderedStatistic(items_base=frozenset({'whole milk', 'pork', 'beef'}), items_add=frozenset({'root vegetables', 'soda'}), confidence=0.3333333333333333, lift=4.0988433228180865)]),
 RelationRecord(items=frozenset({'pork', 'whole milk', 'root vegetables', 'beef', 'yogurt'}), support=0.0030785017957927143, ordered_statistics=[OrderedStatistic(items_base=frozenset({'whole milk', 'pork', 'beef'}), items_add=frozenset({'yogurt', 'root vegetables'}), confidence=0.3333333333333333, lift=4.657108721624851)]),
 RelationRecord(items=frozenset({'pork', 'whole milk', 'soda', 'beef', 'yogurt'}), support=0.004104669061056952, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pork', 'beef'}), items_add=frozenset({'whole milk', 'yogurt', 'soda'}), confidence=0.22535211267605634, lift=4.143502524581451), OrderedStatistic(items_base=frozenset({'whole milk', 'pork', 'beef'}), items_add=frozenset({'yogurt', 'soda'}), confidence=0.4444444444444444, lift=4.5590643274853795), OrderedStatistic(items_base=frozenset({'yogurt', 'soda', 'beef'}), items_add=frozenset({'whole milk', 'pork'}), confidence=0.2807017543859649, lift=4.192243059756671)]),
 RelationRecord(items=frozenset({'whipped/sour cream', 'whole milk', 'sausage', 'beef', 'yogurt'}), support=0.0033350436121087736, ordered_statistics=[OrderedStatistic(items_base=frozenset({'whole milk', 'sausage', 'beef'}), items_add=frozenset({'yogurt', 'whipped/sour cream'}), confidence=0.2096774193548387, lift=4.370708987407279)]),
 RelationRecord(items=frozenset({'other vegetables', 'whole milk', 'bottled water', 'pip fruit', 'berries'}), support=0.0030785017957927143, ordered_statistics=[OrderedStatistic(items_base=frozenset({'whole milk', 'bottled water', 'berries'}), items_add=frozenset({'other vegetables', 'pip fruit'}), confidence=0.29268292682926833, lift=4.0456668396471205)]),
 RelationRecord(items=frozenset({'pork', 'whole milk', 'bottled water', 'yogurt', 'berries'}), support=0.0030785017957927143, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pork', 'berries'}), items_add=frozenset({'whole milk', 'yogurt', 'bottled water'}), confidence=0.24, lift=5.958726114649681), OrderedStatistic(items_base=frozenset({'pork', 'bottled water', 'berries'}), items_add=frozenset({'whole milk', 'yogurt'}), confidence=0.7058823529411765, lift=4.687443631626415), OrderedStatistic(items_base=frozenset({'whole milk', 'bottled water', 'berries'}), items_add=frozenset({'yogurt', 'pork'}), confidence=0.29268292682926833, lift=6.914412416851442), OrderedStatistic(items_base=frozenset({'yogurt', 'bottled water', 'berries'}), items_add=frozenset({'whole milk', 'pork'}), confidence=0.375, lift=5.600574712643678), OrderedStatistic(items_base=frozenset({'whole milk', 'pork', 'berries'}), items_add=frozenset({'yogurt', 'bottled water'}), confidence=0.3870967741935484, lift=5.8258811807198905), OrderedStatistic(items_base=frozenset({'yogurt', 'pork', 'berries'}), items_add=frozenset({'whole milk', 'bottled water'}), confidence=0.5217391304347826, lift=4.643240023823704), OrderedStatistic(items_base=frozenset({'whole milk', 'pork', 'bottled water'}), items_add=frozenset({'yogurt', 'berries'}), confidence=0.2181818181818182, lift=8.952344497607656), OrderedStatistic(items_base=frozenset({'yogurt', 'pork', 'bottled water'}), items_add=frozenset({'whole milk', 'berries'}), confidence=0.3, lift=7.64313725490196), OrderedStatistic(items_base=frozenset({'whole milk', 'yogurt', 'pork', 'bottled water'}), items_add=frozenset({'berries'}), confidence=0.46153846153846156, lift=5.784813257482068)]),
 RelationRecord(items=frozenset({'other vegetables', 'soda', 'pip fruit', 'shopping bags', 'berries'}), support=0.0030785017957927143, ordered_statistics=[OrderedStatistic(items_base=frozenset({'other vegetables', 'berries', 'pip fruit'}), items_add=frozenset({'shopping bags', 'soda'}), confidence=0.2857142857142857, lift=4.419501133786848), OrderedStatistic(items_base=frozenset({'shopping bags', 'other vegetables', 'berries'}), items_add=frozenset({'soda', 'pip fruit'}), confidence=0.32432432432432434, lift=5.3568483737975265), OrderedStatistic(items_base=frozenset({'soda', 'other vegetables', 'berries'}), items_add=frozenset({'shopping bags', 'pip fruit'}), confidence=0.24, lift=7.5445161290322575), OrderedStatistic(items_base=frozenset({'shopping bags', 'berries', 'pip fruit'}), items_add=frozenset({'soda', 'other vegetables'}), confidence=0.5217391304347826, lift=4.201940352137981), OrderedStatistic(items_base=frozenset({'soda', 'berries', 'pip fruit'}), items_add=frozenset({'shopping bags', 'other vegetables'}), confidence=0.4, lift=5.4708771929824564), OrderedStatistic(items_base=frozenset({'shopping bags', 'berries', 'soda'}), items_add=frozenset({'other vegetables', 'pip fruit'}), confidence=0.32432432432432434, lift=4.483036227717079), OrderedStatistic(items_base=frozenset({'shopping bags', 'soda', 'pip fruit'}), items_add=frozenset({'other vegetables', 'berries'}), confidence=0.20338983050847456, lift=5.505649717514124), OrderedStatistic(items_base=frozenset({'shopping bags', 'other vegetables', 'soda', 'pip fruit'}), items_add=frozenset({'berries'}), confidence=0.3636363636363636, lift=4.557731657410113)]),
 RelationRecord(items=frozenset({'whole milk', 'soda', 'shopping bags', 'yogurt', 'berries'}), support=0.0033350436121087736, ordered_statistics=[OrderedStatistic(items_base=frozenset({'whole milk', 'soda', 'berries'}), items_add=frozenset({'yogurt', 'shopping bags'}), confidence=0.23214285714285712, lift=4.228471295060079)]),
 RelationRecord(items=frozenset({'pork', 'other vegetables', 'whole milk', 'soda', 'beverages'}), support=0.0030785017957927143, ordered_statistics=[OrderedStatistic(items_base=frozenset({'beverages', 'pork'}), items_add=frozenset({'whole milk', 'soda', 'other vegetables'}), confidence=0.3076923076923077, lift=4.442165242165243), OrderedStatistic(items_base=frozenset({'beverages', 'pork', 'other vegetables'}), items_add=frozenset({'whole milk', 'soda'}), confidence=0.6315789473684211, lift=4.179787329103744), OrderedStatistic(items_base=frozenset({'beverages', 'other vegetables', 'whole milk'}), items_add=frozenset({'soda', 'pork'}), confidence=0.23529411764705882, lift=5.152676801057502), OrderedStatistic(items_base=frozenset({'beverages', 'pork', 'whole milk'}), items_add=frozenset({'soda', 'other vegetables'}), confidence=0.5454545454545455, lift=4.3929376408715255), OrderedStatistic(items_base=frozenset({'beverages', 'soda', 'whole milk'}), items_add=frozenset({'pork', 'other vegetables'}), confidence=0.23529411764705882, lift=4.226619680130116)]),
 RelationRecord(items=frozenset({'whole milk', 'sausage', 'bottled water', 'brown bread', 'bottled beer'}), support=0.0030785017957927143, ordered_statistics=[OrderedStatistic(items_base=frozenset({'whole milk', 'brown bread', 'bottled beer'}), items_add=frozenset({'sausage', 'bottled water'}), confidence=0.21428571428571427, lift=4.350446428571428)]),
 RelationRecord(items=frozenset({'ham', 'whole milk', 'rolls/buns', 'yogurt', 'bottled beer'}), support=0.0030785017957927143, ordered_statistics=[OrderedStatistic(items_base=frozenset({'rolls/buns', 'yogurt', 'ham'}), items_add=frozenset({'whole milk', 'bottled beer'}), confidence=0.34285714285714286, lift=4.013384813384813)]),
 RelationRecord(items=frozenset({'whipped/sour cream', 'sausage', 'rolls/buns', 'yogurt', 'bottled beer'}), support=0.0030785017957927143, ordered_statistics=[OrderedStatistic(items_base=frozenset({'rolls/buns', 'sausage', 'whipped/sour cream'}), items_add=frozenset({'yogurt', 'bottled beer'}), confidence=0.22222222222222224, lift=4.55906432748538)]),

In [69]:
# record => items, support, ordered_stat, item_add, confidence, lift
(rules[0])

RelationRecord(items=frozenset({'beverages', 'canned beer', 'meat'}), support=0.0030785017957927143, ordered_statistics=[OrderedStatistic(items_base=frozenset({'beverages', 'canned beer'}), items_add=frozenset({'meat'}), confidence=0.27906976744186046, lift=4.3863465866466615)])

In [70]:
len(rules)

90

In [71]:
# print for details
def print_rules(rules):
    for rule in rules:
        print ('rule.items=', list(rule.items))
        print ('rule.support=',rule.support)

        for os in rule.ordered_statistics:
            print ('\titems_base=', list(os.items_base))
            print ('\tlifted_item =', list(os.items_add))
            print ('\tlift=', os.lift)
            print ('\tconfidence (i.e. cond prob {} if {})='.format(list(os.items_add), list(os.items_base)), os.confidence)
            print ('\n')

In [72]:
print_rules(rules)

rule.items= ['beverages', 'canned beer', 'meat']
rule.support= 0.0030785017957927143
	items_base= ['beverages', 'canned beer']
	lifted_item = ['meat']
	lift= 4.3863465866466615
	confidence (i.e. cond prob ['meat'] if ['beverages', 'canned beer'])= 0.27906976744186046


rule.items= ['red/blush wine', 'dessert', 'pastry']
rule.support= 0.0035915854284248334
	items_base= ['red/blush wine', 'pastry']
	lifted_item = ['dessert']
	lift= 4.152172258997185
	confidence (i.e. cond prob ['dessert'] if ['red/blush wine', 'pastry'])= 0.358974358974359


rule.items= ['whole milk', 'meat spreads', 'domestic eggs']
rule.support= 0.0033350436121087736
	items_base= ['meat spreads']
	lifted_item = ['whole milk', 'domestic eggs']
	lift= 5.284045881126173
	confidence (i.e. cond prob ['whole milk', 'domestic eggs'] if ['meat spreads'])= 0.37142857142857144


rule.items= ['onions', 'sausage', 'sliced cheese']
rule.support= 0.0035915854284248334
	items_base= ['onions', 'sausage']
	lifted_item = ['sliced cheese']
	lift= 4.093309330933093
	confidence (i.e. cond prob ['sliced cheese'] if ['onions', 'sausage'])= 0.2121212121212121


rule.items= ['sugar', 'other vegetables', 'spread cheese']
rule.support= 0.0030785017957927143
	items_base= ['other vegetables', 'spread cheese']
	lifted_item = ['sugar']
	lift= 4.04461738002594
	confidence (i.e. cond prob ['sugar'] if ['other vegetables', 'spread cheese'])= 0.26666666666666666


rule.items= ['frankfurter', 'other vegetables', 'margarine', 'UHT-milk']
rule.support= 0.0030785017957927143
	items_base= ['frankfurter', 'UHT-milk']
	lifted_item = ['margarine', 'other vegetables']
	lift= 4.065710560625814
	confidence (i.e. cond prob ['margarine', 'other vegetables'] if ['frankfurter', 'UHT-milk'])= 0.20338983050847456


	items_base= ['margarine', 'UHT-milk']
	lifted_item = ['frankfurter', 'other vegetables']
	lift= 4.2725611983924
	confidence (i.e. cond prob ['frankfurter', 'other vegetables'] if ['margarine', 'UHT-milk'])= 0.2608695652173913


rule.items= ['shopping bags', 'bottled water', 'berries', 'pip fruit']
rule.support= 0.0030785017957927143
	items_base= ['shopping bags', 'bottled water', 'pip fruit']
	lifted_item = ['berries']
	lift= 4.0650039106630755
	confidence (i.e. cond prob ['berries'] if ['shopping bags', 'bottled water', 'pip fruit'])= 0.32432432432432434


rule.items= ['yogurt', 'pork', 'bottled water', 'berries']
rule.support= 0.0033350436121087736
	items_base= ['yogurt', 'pork', 'bottled water']
	lifted_item = ['berries']
	lift= 4.07347266881029
	confidence (i.e. cond prob ['berries'] if ['yogurt', 'pork', 'bottled water'])= 0.325


rule.items= ['pip fruit', 'other vegetables', 'berries', 'fruit/vegetable juice']
rule.support= 0.0038481272447408927
	items_base= ['berries', 'pip fruit']
	lifted_item = ['other vegetables', 'fruit/vegetable juice']
	lift= 4.017176228100309
	confidence (i.e. cond prob ['other vegetables', 'fruit/vegetable juice'] if ['berries', 'pip fruit'])= 0.21126760563380284


	items_base= ['pip fruit', 'other vegetables', 'fruit/vegetable juice']
	lifted_item = ['berries']
	lift= 4.00013682698228
	confidence (i.e. cond prob ['berries'] if ['pip fruit', 'other vegetables', 'fruit/vegetable juice'])= 0.3191489361702127


rule.items= ['rolls/buns', 'beverages', 'oil', 'other vegetables']
rule.support= 0.0030785017957927143
	items_base= ['rolls/buns', 'beverages', 'other vegetables']
	lifted_item = ['oil']
	lift= 4.0671245978610555
	confidence (i.e. cond prob ['oil'] if ['rolls/buns', 'beverages', 'other vegetables'])= 0.22641509433962265


	items_base= ['rolls/buns', 'oil', 'other vegetables']
	lifted_item = ['beverages']
	lift= 4.956134774316593
	confidence (i.e. cond prob ['beverages'] if ['rolls/buns', 'oil', 'other vegetables'])= 0.3076923076923077


rule.items= ['sausage', 'waffles', 'tropical fruit', 'bottled beer']
rule.support= 0.0033350436121087736
	items_base= ['sausage', 'waffles']
	lifted_item = ['tropical fruit', 'bottled beer']
	lift= 4.894147189491983
	confidence (i.e. cond prob ['tropical fruit', 'bottled beer'] if ['sausage', 'waffles'])= 0.2096774193548387


	items_base= ['sausage', 'tropical fruit', 'bottled beer']
	lifted_item = ['waffles']
	lift= 4.281345049003042
	confidence (i.e. cond prob ['waffles'] if ['sausage', 'tropical fruit', 'bottled beer'])= 0.29545454545454547


rule.items= ['white bread', 'soda', 'bottled beer', 'whipped/sour cream']
rule.support= 0.0033350436121087736
	items_base= ['white bread', 'bottled beer']
	lifted_item = ['soda', 'whipped/sour cream']
	lift= 4.124867724867725
	confidence (i.e. cond prob ['soda', 'whipped/sour cream'] if ['white bread', 'bottled beer'])= 0.2


rule.items= ['other vegetables', 'oil', 'bottled water', 'chocolate']
rule.support= 0.0033350436121087736
	items_base= ['oil', 'bottled water']
	lifted_item = ['other vegetables', 'chocolate']
	lift= 6.374088050314465
	confidence (i.e. cond prob ['other vegetables', 'chocolate'] if ['oil', 'bottled water'])= 0.2452830188679245


	items_base= ['oil', 'chocolate']
	lifted_item = ['other vegetables', 'bottled water']
	lift= 4.774260410778218
	confidence (i.e. cond prob ['other vegetables', 'bottled water'] if ['oil', 'chocolate'])= 0.4482758620689655


	items_base= ['other vegetables', 'bottled water', 'chocolate']
	lifted_item = ['oil']
	lift= 4.406051647682809
	confidence (i.e. cond prob ['oil'] if ['other vegetables', 'bottled water', 'chocolate'])= 0.2452830188679245


	items_base= ['other vegetables', 'oil', 'bottled water']
	lifted_item = ['chocolate']
	lift= 5.012265084075174
	confidence (i.e. cond prob ['chocolate'] if ['other vegetables', 'oil', 'bottled water'])= 0.43333333333333335


rule.items= ['sausage', 'citrus fruit', 'bottled water', 'sugar']
rule.support= 0.0030785017957927143
	items_base= ['sausage', 'citrus fruit', 'bottled water']
	lifted_item = ['sugar']
	lift= 4.550194552529183
	confidence (i.e. cond prob ['sugar'] if ['sausage', 'citrus fruit', 'bottled water'])= 0.3


rule.items= ['yogurt', 'citrus fruit', 'bottled water', 'specialty chocolate']
rule.support= 0.0038481272447408927
	items_base= ['specialty chocolate', 'bottled water']
	lifted_item = ['yogurt', 'citrus fruit']
	lift= 4.088525277952591
	confidence (i.e. cond prob ['yogurt', 'citrus fruit'] if ['specialty chocolate', 'bottled water'])= 0.2380952380952381


	items_base= ['yogurt', 'specialty chocolate']
	lifted_item = ['citrus fruit', 'bottled water']
	lift= 5.3583211143695015
	confidence (i.e. cond prob ['citrus fruit', 'bottled water'] if ['yogurt', 'specialty chocolate'])= 0.24193548387096772


	items_base= ['yogurt', 'citrus fruit', 'bottled water']
	lifted_item = ['specialty chocolate']
	lift= 4.136247877758913
	confidence (i.e. cond prob ['specialty chocolate'] if ['yogurt', 'citrus fruit', 'bottled water'])= 0.24193548387096772


rule.items= ['canned beer', 'curd', 'other vegetables', 'salty snack']
rule.support= 0.0030785017957927143
	items_base= ['curd', 'salty snack']
	lifted_item = ['canned beer', 'other vegetables']
	lift= 4.057598889659959
	confidence (i.e. cond prob ['canned beer', 'other vegetables'] if ['curd', 'salty snack'])= 0.27272727272727276


rule.items= ['yogurt', 'other vegetables', 'cat food', 'fruit/vegetable juice']
rule.support= 0.0030785017957927143
	items_base= ['yogurt', 'cat food']
	lifted_item = ['other vegetables', 'fruit/vegetable juice']
	lift= 4.305200184077313
	confidence (i.e. cond prob ['other vegetables', 'fruit/vegetable juice'] if ['yogurt', 'cat food'])= 0.22641509433962265


rule.items= ['rolls/buns', 'yogurt', 'chewing gum', 'domestic eggs']
rule.support= 0.0035915854284248334
	items_base= ['rolls/buns', 'chewing gum']
	lifted_item = ['yogurt', 'domestic eggs']
	lift= 4.6130177514792905
	confidence (i.e. cond prob ['yogurt', 'domestic eggs'] if ['rolls/buns', 'chewing gum'])= 0.2


rule.items= ['citrus fruit', 'oil', 'other vegetables', 'chocolate']
rule.support= 0.0033350436121087736
	items_base= ['oil', 'chocolate']
	lifted_item = ['citrus fruit', 'other vegetables']
	lift= 5.786024206439826
	confidence (i.e. cond prob ['citrus fruit', 'other vegetables'] if ['oil', 'chocolate'])= 0.4482758620689655


	items_base= ['citrus fruit', 'oil']
	lifted_item = ['other vegetables', 'chocolate']
	lift= 6.374088050314465
	confidence (i.e. cond prob ['other vegetables', 'chocolate'] if ['citrus fruit', 'oil'])= 0.2452830188679245


	items_base= ['citrus fruit', 'other vegetables', 'chocolate']
	lifted_item = ['oil']
	lift= 5.838018433179723
	confidence (i.e. cond prob ['oil'] if ['citrus fruit', 'other vegetables', 'chocolate'])= 0.325


	items_base= ['citrus fruit', 'oil', 'other vegetables']
	lifted_item = ['chocolate']
	lift= 5.012265084075174
	confidence (i.e. cond prob ['chocolate'] if ['citrus fruit', 'oil', 'other vegetables'])= 0.43333333333333335


rule.items= ['frankfurter', 'grapes', 'citrus fruit', 'other vegetables']
rule.support= 0.0030785017957927143
	items_base= ['grapes', 'citrus fruit']
	lifted_item = ['frankfurter', 'other vegetables']
	lift= 4.36750700280112
	confidence (i.e. cond prob ['frankfurter', 'other vegetables'] if ['grapes', 'citrus fruit'])= 0.26666666666666666


rule.items= ['rolls/buns', 'white bread', 'sausage', 'dessert']
rule.support= 0.0033350436121087736
	items_base= ['white bread', 'dessert']
	lifted_item = ['rolls/buns', 'sausage']
	lift= 4.154287588129202
	confidence (i.e. cond prob ['rolls/buns', 'sausage'] if ['white bread', 'dessert'])= 0.34210526315789475


rule.items= ['rolls/buns', 'white bread', 'shopping bags', 'dessert']
rule.support= 0.0033350436121087736
	items_base= ['shopping bags', 'dessert']
	lifted_item = ['rolls/buns', 'white bread']
	lift= 5.56001755540926
	confidence (i.e. cond prob ['rolls/buns', 'white bread'] if ['shopping bags', 'dessert'])= 0.2096774193548387


	items_base= ['white bread', 'dessert']
	lifted_item = ['rolls/buns', 'shopping bags']
	lift= 4.975844461901021
	confidence (i.e. cond prob ['rolls/buns', 'shopping bags'] if ['white bread', 'dessert'])= 0.34210526315789475


	items_base= ['rolls/buns', 'shopping bags', 'dessert']
	lifted_item = ['white bread']
	lift= 5.424320274031256
	confidence (i.e. cond prob ['white bread'] if ['rolls/buns', 'shopping bags', 'dessert'])= 0.48148148148148145


	items_base= ['rolls/buns', 'white bread', 'shopping bags']
	lifted_item = ['dessert']
	lift= 4.176887570062644
	confidence (i.e. cond prob ['dessert'] if ['rolls/buns', 'white bread', 'shopping bags'])= 0.36111111111111105


rule.items= ['other vegetables', 'soda', 'waffles', 'hamburger meat']
rule.support= 0.0033350436121087736
	items_base= ['waffles', 'hamburger meat']
	lifted_item = ['soda', 'other vegetables']
	lift= 4.362431129476584
	confidence (i.e. cond prob ['soda', 'other vegetables'] if ['waffles', 'hamburger meat'])= 0.5416666666666666


rule.items= ['waffles', 'pork', 'other vegetables', 'pip fruit']
rule.support= 0.0030785017957927143
	items_base= ['waffles', 'pork']
	lifted_item = ['other vegetables', 'pip fruit']
	lift= 4.253136933987998
	confidence (i.e. cond prob ['other vegetables', 'pip fruit'] if ['waffles', 'pork'])= 0.3076923076923077


rule.items= ['whole milk', 'waffles', 'pork', 'pip fruit']
rule.support= 0.0035915854284248334
	items_base= ['waffles', 'pork']
	lifted_item = ['whole milk', 'pip fruit']
	lift= 4.127675667498676
	confidence (i.e. cond prob ['whole milk', 'pip fruit'] if ['waffles', 'pork'])= 0.358974358974359


rule.items= ['whole milk', 'yogurt', 'waffles', 'sliced cheese']
rule.support= 0.0030785017957927143
	items_base= ['waffles', 'sliced cheese']
	lifted_item = ['whole milk', 'yogurt']
	lift= 5.312436115843271
	confidence (i.e. cond prob ['whole milk', 'yogurt'] if ['waffles', 'sliced cheese'])= 0.8


	items_base= ['whole milk', 'yogurt', 'sliced cheese']
	lifted_item = ['waffles']
	lift= 4.347211895910781
	confidence (i.e. cond prob ['waffles'] if ['whole milk', 'yogurt', 'sliced cheese'])= 0.3


rule.items= ['sausage', 'soda', 'rolls/buns', 'UHT-milk', 'yogurt']
rule.support= 0.0030785017957927143
	items_base= ['sausage', 'UHT-milk', 'soda']
	lifted_item = ['rolls/buns', 'yogurt']
	lift= 4.490783410138248
	confidence (i.e. cond prob ['rolls/buns', 'yogurt'] if ['sausage', 'UHT-milk', 'soda'])= 0.5


rule.items= ['pork', 'other vegetables', 'beef', 'rolls/buns', 'yogurt']
rule.support= 0.0033350436121087736
	items_base= ['rolls/buns', 'yogurt', 'beef']
	lifted_item = ['pork', 'other vegetables']
	lift= 4.245831587767071
	confidence (i.e. cond prob ['pork', 'other vegetables'] if ['rolls/buns', 'yogurt', 'beef'])= 0.23636363636363636


rule.items= ['pork', 'soda', 'beef', 'rolls/buns', 'yogurt']
rule.support= 0.0030785017957927143
	items_base= ['rolls/buns', 'yogurt', 'beef']
	lifted_item = ['soda', 'pork']
	lift= 4.777936670071502
	confidence (i.e. cond prob ['soda', 'pork'] if ['rolls/buns', 'yogurt', 'beef'])= 0.2181818181818182


	items_base= ['yogurt', 'soda', 'beef']
	lifted_item = ['rolls/buns', 'pork']
	lift= 4.435846372688478
	confidence (i.e. cond prob ['rolls/buns', 'pork'] if ['yogurt', 'soda', 'beef'])= 0.2105263157894737


rule.items= ['pork', 'whole milk', 'root vegetables', 'soda', 'beef']
rule.support= 0.0030785017957927143
	items_base= ['whole milk', 'pork', 'beef']
	lifted_item = ['root vegetables', 'soda']
	lift= 4.0988433228180865
	confidence (i.e. cond prob ['root vegetables', 'soda'] if ['whole milk', 'pork', 'beef'])= 0.3333333333333333


rule.items= ['pork', 'whole milk', 'root vegetables', 'beef', 'yogurt']
rule.support= 0.0030785017957927143
	items_base= ['whole milk', 'pork', 'beef']
	lifted_item = ['yogurt', 'root vegetables']
	lift= 4.657108721624851
	confidence (i.e. cond prob ['yogurt', 'root vegetables'] if ['whole milk', 'pork', 'beef'])= 0.3333333333333333


rule.items= ['pork', 'whole milk', 'soda', 'beef', 'yogurt']
rule.support= 0.004104669061056952
	items_base= ['pork', 'beef']
	lifted_item = ['whole milk', 'yogurt', 'soda']
	lift= 4.143502524581451
	confidence (i.e. cond prob ['whole milk', 'yogurt', 'soda'] if ['pork', 'beef'])= 0.22535211267605634


	items_base= ['whole milk', 'pork', 'beef']
	lifted_item = ['yogurt', 'soda']
	lift= 4.5590643274853795
	confidence (i.e. cond prob ['yogurt', 'soda'] if ['whole milk', 'pork', 'beef'])= 0.4444444444444444


	items_base= ['yogurt', 'soda', 'beef']
	lifted_item = ['whole milk', 'pork']
	lift= 4.192243059756671
	confidence (i.e. cond prob ['whole milk', 'pork'] if ['yogurt', 'soda', 'beef'])= 0.2807017543859649


rule.items= ['whipped/sour cream', 'whole milk', 'sausage', 'beef', 'yogurt']
rule.support= 0.0033350436121087736
	items_base= ['whole milk', 'sausage', 'beef']
	lifted_item = ['yogurt', 'whipped/sour cream']
	lift= 4.370708987407279
	confidence (i.e. cond prob ['yogurt', 'whipped/sour cream'] if ['whole milk', 'sausage', 'beef'])= 0.2096774193548387


rule.items= ['other vegetables', 'whole milk', 'bottled water', 'pip fruit', 'berries']
rule.support= 0.0030785017957927143
	items_base= ['whole milk', 'bottled water', 'berries']
	lifted_item = ['other vegetables', 'pip fruit']
	lift= 4.0456668396471205
	confidence (i.e. cond prob ['other vegetables', 'pip fruit'] if ['whole milk', 'bottled water', 'berries'])= 0.29268292682926833


rule.items= ['pork', 'whole milk', 'bottled water', 'yogurt', 'berries']
rule.support= 0.0030785017957927143
	items_base= ['pork', 'berries']
	lifted_item = ['whole milk', 'yogurt', 'bottled water']
	lift= 5.958726114649681
	confidence (i.e. cond prob ['whole milk', 'yogurt', 'bottled water'] if ['pork', 'berries'])= 0.24


	items_base= ['pork', 'bottled water', 'berries']
	lifted_item = ['whole milk', 'yogurt']
	lift= 4.687443631626415
	confidence (i.e. cond prob ['whole milk', 'yogurt'] if ['pork', 'bottled water', 'berries'])= 0.7058823529411765


	items_base= ['whole milk', 'bottled water', 'berries']
	lifted_item = ['yogurt', 'pork']
	lift= 6.914412416851442
	confidence (i.e. cond prob ['yogurt', 'pork'] if ['whole milk', 'bottled water', 'berries'])= 0.29268292682926833


	items_base= ['yogurt', 'bottled water', 'berries']
	lifted_item = ['whole milk', 'pork']
	lift= 5.600574712643678
	confidence (i.e. cond prob ['whole milk', 'pork'] if ['yogurt', 'bottled water', 'berries'])= 0.375


	items_base= ['whole milk', 'pork', 'berries']
	lifted_item = ['yogurt', 'bottled water']
	lift= 5.8258811807198905
	confidence (i.e. cond prob ['yogurt', 'bottled water'] if ['whole milk', 'pork', 'berries'])= 0.3870967741935484


	items_base= ['yogurt', 'pork', 'berries']
	lifted_item = ['whole milk', 'bottled water']
	lift= 4.643240023823704
	confidence (i.e. cond prob ['whole milk', 'bottled water'] if ['yogurt', 'pork', 'berries'])= 0.5217391304347826


	items_base= ['whole milk', 'pork', 'bottled water']
	lifted_item = ['yogurt', 'berries']
	lift= 8.952344497607656
	confidence (i.e. cond prob ['yogurt', 'berries'] if ['whole milk', 'pork', 'bottled water'])= 0.2181818181818182


	items_base= ['yogurt', 'pork', 'bottled water']
	lifted_item = ['whole milk', 'berries']
	lift= 7.64313725490196
	confidence (i.e. cond prob ['whole milk', 'berries'] if ['yogurt', 'pork', 'bottled water'])= 0.3


	items_base= ['whole milk', 'yogurt', 'pork', 'bottled water']
	lifted_item = ['berries']
	lift= 5.784813257482068
	confidence (i.e. cond prob ['berries'] if ['whole milk', 'yogurt', 'pork', 'bottled water'])= 0.46153846153846156


rule.items= ['other vegetables', 'soda', 'pip fruit', 'shopping bags', 'berries']
rule.support= 0.0030785017957927143
	items_base= ['other vegetables', 'berries', 'pip fruit']
	lifted_item = ['shopping bags', 'soda']
	lift= 4.419501133786848
	confidence (i.e. cond prob ['shopping bags', 'soda'] if ['other vegetables', 'berries', 'pip fruit'])= 0.2857142857142857


	items_base= ['shopping bags', 'other vegetables', 'berries']
	lifted_item = ['soda', 'pip fruit']
	lift= 5.3568483737975265
	confidence (i.e. cond prob ['soda', 'pip fruit'] if ['shopping bags', 'other vegetables', 'berries'])= 0.32432432432432434


	items_base= ['soda', 'other vegetables', 'berries']
	lifted_item = ['shopping bags', 'pip fruit']
	lift= 7.5445161290322575
	confidence (i.e. cond prob ['shopping bags', 'pip fruit'] if ['soda', 'other vegetables', 'berries'])= 0.24


	items_base= ['shopping bags', 'berries', 'pip fruit']
	lifted_item = ['soda', 'other vegetables']
	lift= 4.201940352137981
	confidence (i.e. cond prob ['soda', 'other vegetables'] if ['shopping bags', 'berries', 'pip fruit'])= 0.5217391304347826


	items_base= ['soda', 'berries', 'pip fruit']
	lifted_item = ['shopping bags', 'other vegetables']
	lift= 5.4708771929824564
	confidence (i.e. cond prob ['shopping bags', 'other vegetables'] if ['soda', 'berries', 'pip fruit'])= 0.4


	items_base= ['shopping bags', 'berries', 'soda']
	lifted_item = ['other vegetables', 'pip fruit']
	lift= 4.483036227717079
	confidence (i.e. cond prob ['other vegetables', 'pip fruit'] if ['shopping bags', 'berries', 'soda'])= 0.32432432432432434


	items_base= ['shopping bags', 'soda', 'pip fruit']
	lifted_item = ['other vegetables', 'berries']
	lift= 5.505649717514124
	confidence (i.e. cond prob ['other vegetables', 'berries'] if ['shopping bags', 'soda', 'pip fruit'])= 0.20338983050847456


	items_base= ['shopping bags', 'other vegetables', 'soda', 'pip fruit']
	lifted_item = ['berries']
	lift= 4.557731657410113
	confidence (i.e. cond prob ['berries'] if ['shopping bags', 'other vegetables', 'soda', 'pip fruit'])= 0.3636363636363636


rule.items= ['whole milk', 'soda', 'shopping bags', 'yogurt', 'berries']
rule.support= 0.0033350436121087736
	items_base= ['whole milk', 'soda', 'berries']
	lifted_item = ['yogurt', 'shopping bags']
	lift= 4.228471295060079
	confidence (i.e. cond prob ['yogurt', 'shopping bags'] if ['whole milk', 'soda', 'berries'])= 0.23214285714285712


rule.items= ['pork', 'other vegetables', 'whole milk', 'soda', 'beverages']
rule.support= 0.0030785017957927143
	items_base= ['beverages', 'pork']
	lifted_item = ['whole milk', 'soda', 'other vegetables']

In [73]:
def print_rules_multi_os(rules):
    for rule in rules:
        if len (rule.ordered_statistics)>1:  
            print ('rule.items=', list(rule.items))
            for os in rule.ordered_statistics:
                print ('\n\titems_base=', list(os.items_base))
                print ('\tlifted_item =', list(os.items_add))
                print ('\tlift=', os.lift)
                print ('\tconfidence (i.e. cond prob {} if {})='.format(list(os.items_add), list(os.items_base)), os.confidence)

            break

In [74]:
print_rules_multi_os(rules)

rule.items= ['frankfurter', 'other vegetables', 'margarine', 'UHT-milk']

	items_base= ['frankfurter', 'UHT-milk']
	lifted_item = ['margarine', 'other vegetables']
	lift= 4.065710560625814
	confidence (i.e. cond prob ['margarine', 'other vegetables'] if ['frankfurter', 'UHT-milk'])= 0.20338983050847456

	items_base= ['margarine', 'UHT-milk']
	lifted_item = ['frankfurter', 'other vegetables']
	lift= 4.2725611983924
	confidence (i.e. cond prob ['frankfurter', 'other vegetables'] if ['margarine', 'UHT-milk'])= 0.2608695652173913

In [76]:
def get_confidence(rule):
    return max(ordered_stat.confidence for ordered_stat in rule.ordered_statistics)

In [77]:
# i select best by confidence parametet
sorted_rules = sorted(rules, key=get_confidence, reverse=True)

In [78]:
top_10_rules = sorted_rules[:10]

In [79]:
# print top 10 rules by confidence
for rule in top_10_rules:
    items = list(rule.items)
    print(f"Rule: {items}, Support: {rule.support:.2f}")
    for ordered_stat in rule.ordered_statistics:
        base = list(ordered_stat.items_base)
        add = list(ordered_stat.items_add)
        print(f"  {base} => {add}")
        print(f"  Confidence: {ordered_stat.confidence:.2f}, Lift: {ordered_stat.lift:.2f}")
    print()

Rule: ['whole milk', 'yogurt', 'waffles', 'sliced cheese'], Support: 0.00
  ['waffles', 'sliced cheese'] => ['whole milk', 'yogurt']
  Confidence: 0.80, Lift: 5.31
  ['whole milk', 'yogurt', 'sliced cheese'] => ['waffles']
  Confidence: 0.30, Lift: 4.35

Rule: ['whole milk', 'soda', 'citrus fruit', 'yogurt', 'specialty chocolate'], Support: 0.00
  ['whole milk', 'soda', 'specialty chocolate'] => ['yogurt', 'citrus fruit']
  Confidence: 0.24, Lift: 4.12
  ['yogurt', 'soda', 'specialty chocolate'] => ['whole milk', 'citrus fruit']
  Confidence: 0.48, Lift: 5.20
  ['whole milk', 'yogurt', 'specialty chocolate'] => ['citrus fruit', 'soda']
  Confidence: 0.32, Lift: 4.98
  ['whole milk', 'yogurt', 'soda', 'specialty chocolate'] => ['citrus fruit']
  Confidence: 0.75, Lift: 4.04

Rule: ['pork', 'whole milk', 'bottled water', 'yogurt', 'berries'], Support: 0.00
  ['pork', 'berries'] => ['whole milk', 'yogurt', 'bottled water']
  Confidence: 0.24, Lift: 5.96
  ['pork', 'bottled water', 'berries'] => ['whole milk', 'yogurt']
  Confidence: 0.71, Lift: 4.69
  ['whole milk', 'bottled water', 'berries'] => ['yogurt', 'pork']
  Confidence: 0.29, Lift: 6.91
  ['yogurt', 'bottled water', 'berries'] => ['whole milk', 'pork']
  Confidence: 0.38, Lift: 5.60
  ['whole milk', 'pork', 'berries'] => ['yogurt', 'bottled water']
  Confidence: 0.39, Lift: 5.83
  ['yogurt', 'pork', 'berries'] => ['whole milk', 'bottled water']
  Confidence: 0.52, Lift: 4.64
  ['whole milk', 'pork', 'bottled water'] => ['yogurt', 'berries']
  Confidence: 0.22, Lift: 8.95
  ['yogurt', 'pork', 'bottled water'] => ['whole milk', 'berries']
  Confidence: 0.30, Lift: 7.64
  ['whole milk', 'yogurt', 'pork', 'bottled water'] => ['berries']
  Confidence: 0.46, Lift: 5.78

Rule: ['pork', 'other vegetables', 'whole milk', 'soda', 'beverages'], Support: 0.00
  ['beverages', 'pork'] => ['whole milk', 'soda', 'other vegetables']
  Confidence: 0.31, Lift: 4.44
  ['beverages', 'pork', 'other vegetables'] => ['whole milk', 'soda']
  Confidence: 0.63, Lift: 4.18
  ['beverages', 'other vegetables', 'whole milk'] => ['soda', 'pork']
  Confidence: 0.24, Lift: 5.15
  ['beverages', 'pork', 'whole milk'] => ['soda', 'other vegetables']
  Confidence: 0.55, Lift: 4.39
  ['beverages', 'soda', 'whole milk'] => ['pork', 'other vegetables']
  Confidence: 0.24, Lift: 4.23

Rule: ['pork', 'other vegetables', 'white bread', 'whole milk', 'soda'], Support: 0.00
  ['white bread', 'pork'] => ['whole milk', 'soda', 'other vegetables']
  Confidence: 0.29, Lift: 4.12
  ['white bread', 'pork', 'other vegetables'] => ['whole milk', 'soda']
  Confidence: 0.61, Lift: 4.03

Rule: ['whole milk', 'brown bread', 'shopping bags', 'yogurt', 'curd'], Support: 0.00
  ['whole milk', 'brown bread', 'curd'] => ['yogurt', 'shopping bags']
  Confidence: 0.25, Lift: 4.47
  ['yogurt', 'brown bread', 'curd'] => ['whole milk', 'shopping bags']
  Confidence: 0.38, Lift: 4.19
  ['yogurt', 'brown bread', 'shopping bags'] => ['whole milk', 'curd']
  Confidence: 0.27, Lift: 4.26
  ['whole milk', 'curd', 'shopping bags'] => ['yogurt', 'brown bread']
  Confidence: 0.23, Lift: 5.52
  ['yogurt', 'curd', 'shopping bags'] => ['whole milk', 'brown bread']
  Confidence: 0.38, Lift: 5.48
  ['yogurt', 'whole milk', 'curd', 'shopping bags'] => ['brown bread']
  Confidence: 0.59, Lift: 4.35

Rule: ['other vegetables', 'sausage', 'root vegetables', 'bottled water', 'soda', 'rolls/buns'], Support: 0.00
  ['sausage', 'root vegetables', 'bottled water'] => ['rolls/buns', 'soda', 'other vegetables']
  Confidence: 0.29, Lift: 5.55
  ['rolls/buns', 'other vegetables', 'soda', 'bottled water'] => ['sausage', 'root vegetables']
  Confidence: 0.23, Lift: 4.15
  ['rolls/buns', 'sausage', 'root vegetables', 'bottled water'] => ['soda', 'other vegetables']
  Confidence: 0.56, Lift: 4.51
  ['rolls/buns', 'sausage', 'bottled water', 'soda'] => ['root vegetables', 'other vegetables']
  Confidence: 0.38, Lift: 4.02
  ['rolls/buns', 'root vegetables', 'other vegetables', 'soda'] => ['sausage', 'bottled water']
  Confidence: 0.23, Lift: 4.66
  ['sausage', 'root vegetables', 'other vegetables', 'soda'] => ['rolls/buns', 'bottled water']
  Confidence: 0.33, Lift: 4.11

Rule: ['whole milk', 'soda', 'brown bread', 'canned beer', 'curd'], Support: 0.00
  ['brown bread', 'curd', 'soda'] => ['whole milk', 'canned beer']
  Confidence: 0.40, Lift: 4.59
  ['whole milk', 'brown bread', 'curd'] => ['canned beer', 'soda']
  Confidence: 0.23, Lift: 4.14
  ['canned beer', 'curd', 'soda'] => ['whole milk', 'brown bread']
  Confidence: 0.35, Lift: 5.06
  ['canned beer', 'curd', 'whole milk'] => ['brown bread', 'soda']
  Confidence: 0.22, Lift: 4.62
  ['canned beer', 'curd', 'soda', 'whole milk'] => ['brown bread']
  Confidence: 0.55, Lift: 4.01

Rule: ['other vegetables', 'soda', 'waffles', 'hamburger meat'], Support: 0.00
  ['waffles', 'hamburger meat'] => ['soda', 'other vegetables']
  Confidence: 0.54, Lift: 4.36

Rule: ['other vegetables', 'soda', 'pip fruit', 'shopping bags', 'berries'], Support: 0.00
  ['other vegetables', 'berries', 'pip fruit'] => ['shopping bags', 'soda']
  Confidence: 0.29, Lift: 4.42
  ['shopping bags', 'other vegetables', 'berries'] => ['soda', 'pip fruit']
  Confidence: 0.32, Lift: 5.36
  ['soda', 'other vegetables', 'berries'] => ['shopping bags', 'pip fruit']
  Confidence: 0.24, Lift: 7.54
  ['shopping bags', 'berries', 'pip fruit'] => ['soda', 'other vegetables']
  Confidence: 0.52, Lift: 4.20
  ['soda', 'berries', 'pip fruit'] => ['shopping bags', 'other vegetables']
  Confidence: 0.40, Lift: 5.47
  ['shopping bags', 'berries', 'soda'] => ['other vegetables', 'pip fruit']
  Confidence: 0.32, Lift: 4.48
  ['shopping bags', 'soda', 'pip fruit'] => ['other vegetables', 'berries']
  Confidence: 0.20, Lift: 5.51
  ['shopping bags', 'other vegetables', 'soda', 'pip fruit'] => ['berries']
  Confidence: 0.36, Lift: 4.56